<template>
  <div class="home">
    <Card dis-hover>
      <Table :data="tableData" :columns="tableColumns"></Table>
    </Card>
  </div>
</template>

<script>
export default {
  name: 'home',
  data() {
    return {
      tableData: [
        {
          id: 3,
          code: '305-A-03',
          city_id: 3,
          city: '北京',
          idc_id: 4,
          idc: '北京_中国电信_永丰',
          building_id: 7,
          building: 'X',
          room_id: 29,
          room: '305',
          power_status: '通电',
          u_num: 45,
          used_u_num: 3,
          rated_current: 20,
          usage_type: '服务器机柜',
          occupy_type_lv1: '独享',
          occupy_type_lv2: '独享',
          rent_time: '0000-00-00 00:00:00',
          surrender_time: '0000-00-00 00:00:00',
          temp_electrified: '未通电',
          borrow_time: '0000-00-00 00:00:00',
          return_time: '0000-00-00 00:00:00',
          basic_code: '',
          status: 'Assigned',
          '16a_outlets': 0,
          '10a_outlets': 25,
          maximum_current: 32,
          remould: '',
          target_surrender_time: '0000-00-00 00:00:00',
          target_rent_time: '0000-00-00 00:00:00',
          order_issue: '',
          temp_contract: 'NWRESOURCE-926',
          service_id: 54,
          application_id: 0,
          business_model_id: 0,
          company_id: 153,
          usage_type_id: 1,
          power_status_id: 1,
          temp_electrified_id: 0,
          occupy_type_lv1_id: 1,
          occupy_type_lv2_id: 1,
          occupy_type_lv1_department: ['京东零售'],
          occupy_type_lv2_department: ['技术与数据中台'],
          outlets_type: ['GB1002-10A'],
          service: '大数据',
          application: null,
          business_model: null,
          company: '中国电信股份有限公司北京分公司',
        },
        {
          id: 5,
          code: '305-A-05',
          city_id: 3,
          city: '北京',
          idc_id: 4,
          idc: '北京_中国电信_永丰',
          building_id: 7,
          building: 'X',
          room_id: 29,
          room: '305',
          power_status: '通电',
          u_num: 45,
          used_u_num: 12,
          rated_current: 20,
          usage_type: '服务器机柜',
          occupy_type_lv1: '独享',
          occupy_type_lv2: '独享',
          rent_time: '0000-00-00 00:00:00',
          surrender_time: '0000-00-00 00:00:00',
          temp_electrified: '未通电',
          borrow_time: '0000-00-00 00:00:00',
          return_time: '0000-00-00 00:00:00',
          basic_code: '',
          status: 'Assigned',
          '16a_outlets': 0,
          '10a_outlets': 25,
          maximum_current: 32,
          remould: '',
          target_surrender_time: '0000-00-00 00:00:00',
          target_rent_time: '0000-00-00 00:00:00',
          order_issue: '',
          temp_contract: 'NWRESOURCE-926',
          service_id: 54,
          application_id: 0,
          business_model_id: 0,
          company_id: 153,
          usage_type_id: 1,
          power_status_id: 1,
          temp_electrified_id: 0,
          occupy_type_lv1_id: 1,
          occupy_type_lv2_id: 1,
          occupy_type_lv1_department: ['京东零售'],
          occupy_type_lv2_department: ['技术与数据中台'],
          outlets_type: ['GB1002-10A'],
          service: '大数据',
          application: null,
          business_model: null,
          company: '中国电信股份有限公司北京分公司',
        },
        {
          id: 6,
          code: '305-A-06',
          city_id: 3,
          city: '北京',
          idc_id: 4,
          idc: '北京_中国电信_永丰',
          building_id: 7,
          building: 'X',
          room_id: 29,
          room: '305',
          power_status: '通电',
          u_num: 45,
          used_u_num: 7,
          rated_current: 20,
          usage_type: '服务器机柜',
          occupy_type_lv1: '独享',
          occupy_type_lv2: '独享',
          rent_time: '0000-00-00 00:00:00',
          surrender_time: '0000-00-00 00:00:00',
          temp_electrified: '未通电',
          borrow_time: '0000-00-00 00:00:00',
          return_time: '0000-00-00 00:00:00',
          basic_code: '',
          status: 'Assigned',
          '16a_outlets': 0,
          '10a_outlets': 25,
          maximum_current: 32,
          remould: '',
          target_surrender_time: '0000-00-00 00:00:00',
          target_rent_time: '0000-00-00 00:00:00',
          order_issue: '',
          temp_contract: 'NWRESOURCE-926',
          service_id: 54,
          application_id: 0,
          business_model_id: 0,
          company_id: 153,
          usage_type_id: 1,
          power_status_id: 1,
          temp_electrified_id: 0,
          occupy_type_lv1_id: 1,
          occupy_type_lv2_id: 1,
          occupy_type_lv1_department: ['京东零售'],
          occupy_type_lv2_department: ['技术与数据中台'],
          outlets_type: ['GB1002-10A'],
          service: '大数据',
          application: null,
          business_model: null,
          company: '中国电信股份有限公司北京分公司',
        },
        {
          id: 7,
          code: '305-A-07',
          city_id: 3,
          city: '北京',
          idc_id: 4,
          idc: '北京_中国电信_永丰',
          building_id: 7,
          building: 'X',
          room_id: 29,
          room: '305',
          power_status: '通电',
          u_num: 45,
          used_u_num: 7,
          rated_current: 20,
          usage_type: '服务器机柜',
          occupy_type_lv1: '共享',
          occupy_type_lv2: '共享',
          rent_time: '0000-00-00 00:00:00',
          surrender_time: '0000-00-00 00:00:00',
          temp_electrified: '未通电',
          borrow_time: '0000-00-00 00:00:00',
          return_time: '0000-00-00 00:00:00',
          basic_code: '',
          status: 'Assigned',
          '16a_outlets': 0,
          '10a_outlets': 25,
          maximum_current: 32,
          remould: '',
          target_surrender_time: '0000-00-00 00:00:00',
          target_rent_time: '0000-00-00 00:00:00',
          order_issue: '',
          temp_contract: 'NWRESOURCE-926',
          service_id: 54,
          application_id: 0,
          business_model_id: 0,
          company_id: 153,
          usage_type_id: 1,
          power_status_id: 1,
          temp_electrified_id: 0,
          occupy_type_lv1_id: 2,
          occupy_type_lv2_id: 2,
          occupy_type_lv1_department: ['京东零售', 'CHO体系', '京东云事业部'],
          occupy_type_lv2_department: [
            '搜索与推荐平台部',
            '企业信息化部',
            '基础研发部',
          ],
          outlets_type: ['GB1002-10A'],
          service: '大数据',
          application: null,
          business_model: null,
          company: '中国电信股份有限公司北京分公司',
        },
        {
          id: 13,
          code: '305-A-13',
          city_id: 3,
          city: '北京',
          idc_id: 4,
          idc: '北京_中国电信_永丰',
          building_id: 7,
          building: 'X',
          room_id: 29,
          room: '305',
          power_status: '通电',
          u_num: 45,
          used_u_num: 6,
          rated_current: 20,
          usage_type: '服务器机柜',
          occupy_type_lv1: '独享',
          occupy_type_lv2: '独享',
          rent_time: '0000-00-00 00:00:00',
          surrender_time: '0000-00-00 00:00:00',
          temp_electrified: '未通电',
          borrow_time: '0000-00-00 00:00:00',
          return_time: '0000-00-00 00:00:00',
          basic_code: '',
          status: 'Assigned',
          '16a_outlets': 0,
          '10a_outlets': 25,
          maximum_current: 32,
          remould: '',
          target_surrender_time: '0000-00-00 00:00:00',
          target_rent_time: '0000-00-00 00:00:00',
          order_issue: '',
          temp_contract: 'NWRESOURCE-926',
          service_id: 54,
          application_id: 0,
          business_model_id: 0,
          company_id: 153,
          usage_type_id: 1,
          power_status_id: 1,
          temp_electrified_id: 0,
          occupy_type_lv1_id: 1,
          occupy_type_lv2_id: 1,
          occupy_type_lv1_department: ['京东零售'],
          occupy_type_lv2_department: ['技术与数据中台'],
          outlets_type: ['GB1002-10A'],
          service: '大数据',
          application: null,
          business_model: null,
          company: '中国电信股份有限公司北京分公司',
        },
        {
          id: 14,
          code: '305-A-14',
          city_id: 3,
          city: '北京',
          idc_id: 4,
          idc: '北京_中国电信_永丰',
          building_id: 7,
          building: 'X',
          room_id: 29,
          room: '305',
          power_status: '通电',
          u_num: 45,
          used_u_num: 9,
          rated_current: 20,
          usage_type: '服务器机柜',
          occupy_type_lv1: '独享',
          occupy_type_lv2: '独享',
          rent_time: '0000-00-00 00:00:00',
          surrender_time: '0000-00-00 00:00:00',
          temp_electrified: '未通电',
          borrow_time: '0000-00-00 00:00:00',
          return_time: '0000-00-00 00:00:00',
          basic_code: '',
          status: 'Assigned',
          '16a_outlets': 0,
          '10a_outlets': 25,
          maximum_current: 32,
          remould: '',
          target_surrender_time: '0000-00-00 00:00:00',
          target_rent_time: '0000-00-00 00:00:00',
          order_issue: '',
          temp_contract: 'NWRESOURCE-926',
          service_id: 54,
          application_id: 0,
          business_model_id: 0,
          company_id: 153,
          usage_type_id: 1,
          power_status_id: 1,
          temp_electrified_id: 0,
          occupy_type_lv1_id: 1,
          occupy_type_lv2_id: 1,
          occupy_type_lv1_department: ['京东零售'],
          occupy_type_lv2_department: ['技术与数据中台'],
          outlets_type: ['GB1002-10A'],
          service: '大数据',
          application: null,
          business_model: null,
          company: '中国电信股份有限公司北京分公司',
        },
        {
          id: 15,
          code: '305-A-15',
          city_id: 3,
          city: '北京',
          idc_id: 4,
          idc: '北京_中国电信_永丰',
          building_id: 7,
          building: 'X',
          room_id: 29,
          room: '305',
          power_status: '通电',
          u_num: 45,
          used_u_num: 11,
          rated_current: 20,
          usage_type: '服务器机柜',
          occupy_type_lv1: '独享',
          occupy_type_lv2: '独享',
          rent_time: '0000-00-00 00:00:00',
          surrender_time: '0000-00-00 00:00:00',
          temp_electrified: '未通电',
          borrow_time: '0000-00-00 00:00:00',
          return_time: '0000-00-00 00:00:00',
          basic_code: '',
          status: 'Assigned',
          '16a_outlets': 0,
          '10a_outlets': 25,
          maximum_current: 32,
          remould: '',
          target_surrender_time: '0000-00-00 00:00:00',
          target_rent_time: '0000-00-00 00:00:00',
          order_issue: '',
          temp_contract: 'NWRESOURCE-926',
          service_id: 54,
          application_id: 0,
          business_model_id: 0,
          company_id: 153,
          usage_type_id: 1,
          power_status_id: 1,
          temp_electrified_id: 0,
          occupy_type_lv1_id: 1,
          occupy_type_lv2_id: 1,
          occupy_type_lv1_department: ['京东零售'],
          occupy_type_lv2_department: ['技术与数据中台'],
          outlets_type: ['GB1002-10A'],
          service: '大数据',
          application: null,
          business_model: null,
          company: '中国电信股份有限公司北京分公司',
        },
        {
          id: 16,
          code: '305-A-16',
          city_id: 3,
          city: '北京',
          idc_id: 4,
          idc: '北京_中国电信_永丰',
          building_id: 7,
          building: 'X',
          room_id: 29,
          room: '305',
          power_status: '通电',
          u_num: 45,
          used_u_num: 11,
          rated_current: 20,
          usage_type: '服务器机柜',
          occupy_type_lv1: '独享',
          occupy_type_lv2: '独享',
          rent_time: '0000-00-00 00:00:00',
          surrender_time: '0000-00-00 00:00:00',
          temp_electrified: '未通电',
          borrow_time: '0000-00-00 00:00:00',
          return_time: '0000-00-00 00:00:00',
          basic_code: '',
          status: 'Assigned',
          '16a_outlets': 0,
          '10a_outlets': 25,
          maximum_current: 32,
          remould: '',
          target_surrender_time: '0000-00-00 00:00:00',
          target_rent_time: '0000-00-00 00:00:00',
          order_issue: '',
          temp_contract: 'NWRESOURCE-926',
          service_id: 54,
          application_id: 0,
          business_model_id: 0,
          company_id: 153,
          usage_type_id: 1,
          power_status_id: 1,
          temp_electrified_id: 0,
          occupy_type_lv1_id: 1,
          occupy_type_lv2_id: 1,
          occupy_type_lv1_department: ['京东零售'],
          occupy_type_lv2_department: ['技术与数据中台'],
          outlets_type: ['GB1002-10A'],
          service: '大数据',
          application: null,
          business_model: null,
          company: '中国电信股份有限公司北京分公司',
        },
        {
          id: 17,
          code: '305-A-17',
          city_id: 3,
          city: '北京',
          idc_id: 4,
          idc: '北京_中国电信_永丰',
          building_id: 7,
          building: 'X',
          room_id: 29,
          room: '305',
          power_status: '通电',
          u_num: 45,
          used_u_num: 6,
          rated_current: 20,
          usage_type: '服务器机柜',
          occupy_type_lv1: '独享',
          occupy_type_lv2: '独享',
          rent_time: '0000-00-00 00:00:00',
          surrender_time: '0000-00-00 00:00:00',
          temp_electrified: '未通电',
          borrow_time: '0000-00-00 00:00:00',
          return_time: '0000-00-00 00:00:00',
          basic_code: '',
          status: 'Assigned',
          '16a_outlets': 0,
          '10a_outlets': 25,
          maximum_current: 32,
          remould: '',
          target_surrender_time: '0000-00-00 00:00:00',
          target_rent_time: '0000-00-00 00:00:00',
          order_issue: '',
          temp_contract: 'NWRESOURCE-926',
          service_id: 54,
          application_id: 0,
          business_model_id: 0,
          company_id: 153,
          usage_type_id: 1,
          power_status_id: 1,
          temp_electrified_id: 0,
          occupy_type_lv1_id: 1,
          occupy_type_lv2_id: 1,
          occupy_type_lv1_department: ['京东零售'],
          occupy_type_lv2_department: ['技术与数据中台'],
          outlets_type: ['GB1002-10A'],
          service: '大数据',
          application: null,
          business_model: null,
          company: '中国电信股份有限公司北京分公司',
        },
        {
          id: 18,
          code: '305-B-01',
          city_id: 3,
          city: '北京',
          idc_id: 4,
          idc: '北京_中国电信_永丰',
          building_id: 7,
          building: 'X',
          room_id: 29,
          room: '305',
          power_status: '通电',
          u_num: 45,
          used_u_num: 6,
          rated_current: 20,
          usage_type: '服务器机柜',
          occupy_type_lv1: '独享',
          occupy_type_lv2: '独享',
          rent_time: '0000-00-00 00:00:00',
          surrender_time: '0000-00-00 00:00:00',
          temp_electrified: '未通电',
          borrow_time: '0000-00-00 00:00:00',
          return_time: '0000-00-00 00:00:00',
          basic_code: '',
          status: 'Assigned',
          '16a_outlets': 0,
          '10a_outlets': 25,
          maximum_current: 32,
          remould: '',
          target_surrender_time: '0000-00-00 00:00:00',
          target_rent_time: '0000-00-00 00:00:00',
          order_issue: '',
          temp_contract: 'NWRESOURCE-926',
          service_id: 54,
          application_id: 0,
          business_model_id: 0,
          company_id: 153,
          usage_type_id: 1,
          power_status_id: 1,
          temp_electrified_id: 0,
          occupy_type_lv1_id: 1,
          occupy_type_lv2_id: 1,
          occupy_type_lv1_department: ['京东零售'],
          occupy_type_lv2_department: ['技术与数据中台'],
          outlets_type: ['GB1002-10A'],
          service: '大数据',
          application: null,
          business_model: null,
          company: '中国电信股份有限公司北京分公司',
        },
      ],
      tableColumns: [
        {
          title: '机柜编码',
          key: 'code',
          render: (h, params)=> {
            return h('router-link', {props: {to: {name: 'cabinetDemo1'}}}, params.row.code)
          }
        },
        {
          title: '机房名称',
          key: 'idc',
        },
        {
          title: '建筑',
          key: 'building',
        },
        {
          title: '房间',
          key: 'room',
        },
        {
          title: '城市',
          key: 'city',
        },
        {
          title: '机架规格',
          key: 'u_num',
        },
        {
          title: '设备使用U数总和',
          key: 'used_u_num',
        },
        {
          title: '合同电流',
          key: 'rated_current',
        },
        {
          title: '服务',
          key: 'service',
        },
        {
          title: '一级使用状态',
          key: 'occupy_type_lv1',
        },
      ],
    };
  },
};
</script>
